sonar.projectKey=Dumidu1212_quickbite_notify-service
sonar.organization=dumidu1212
sonar.projectName=quickbite-notify-service
sonar.sources=app
sonar.tests=tests
sonar.exclusions=**/__pycache__/**,**/.venv/**
