sonar.projectKey=Dumidu1212_quickbite_user-service
sonar.organization=dumidu1212
sonar.projectName=quickbite-user-service
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/coverage/**
